language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements/requirements_devel.txt"
# command to run tests
script:
  - nosetests --with-coverage --cover-package=api
after_success:
  - coveralls
