"""Make all models field not nullable

Revision ID: 1dba23ad33fa
Revises: 63bf3549b550
Create Date: 2017-03-22 06:27:27.017150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dba23ad33fa'
down_revision = '63bf3549b550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlist', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bucketlist', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bucketlist', 'date_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('items', 'bucketlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('items', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('items', 'date_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('items', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'date_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'date_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('items', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('items', 'date_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('items', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('items', 'bucketlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bucketlist', 'date_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bucketlist', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bucketlist', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
