"""unique2

Revision ID: 6e9dd9c6741b
Revises: 0f27b29c51eb
Create Date: 2017-04-08 09:17:57.052048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9dd9c6741b'
down_revision = '0f27b29c51eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'bucketlist_name_key', 'bucketlist', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'bucketlist_name_key', 'bucketlist', ['name'])
    # ### end Alembic commands ###
