"""empty message

Revision ID: 96dedbf66e9c
Revises: 6e9dd9c6741b
Create Date: 2017-04-08 11:22:41.528930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96dedbf66e9c'
down_revision = '6e9dd9c6741b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_constraint_item', 'items', ['name', 'bucketlist_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_constraint_item', 'items', type_='unique')
    # ### end Alembic commands ###
